### ISSUE TITLE
C_REDIR

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#102]
В токенах T_GREAT value = NULL, но в них может быть указан дескриптор, например "2>tmp.txt". То же самое с T_LESS, T_GREATER_GREATER, T_LESS_LESS. В общем везде нужно поле value

**Comment by mmarti42** [comment]
и еще, если у нас есть T_END, то не нужен массив указателей, достаточно массива структур. Можно оставить так, можно переделать - на твое усмотрение

**Comment by mmarti42** [comment]
**Если число перед токеном перенаправления отрицательное, лексер воспринимает его, как аргумент:**
ls -1>&1
*****************************************
token->value = |ls -|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 0
token->end_pos = 4
*****************************************
*****************************************
token->value = |1>&1|
token->type = GREATER_AND
token->class = C_REDIR
token->start_pos = 4
token->end_pos = 8
*****************************************
*****************************************
token->value = NULL
token->type = T_END
token->class = C_END
token->start_pos = 8
token->end_pos = 8
*****************************************

**Должно быть:**
ls -1>&1
*****************************************
token->value = |ls -1|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 0
token->end_pos = 4
*****************************************
*****************************************
token->value = |>&1|
token->type = GREATER_AND
token->class = C_REDIR
token->start_pos = 4
token->end_pos = 8
*****************************************
*****************************************
token->value = NULL
token->type = T_END
token->class = C_END
token->start_pos = 8
token->end_pos = 8
*****************************************

**Comment by mmarti42** [comment]
Оригинальный баш делит команду 1>&2 на токены 1, &>, 2, но, это не совсем удобно. На практике у нас просто будет отличаться сообщение об ошибке. Надеюсь это для вас не принципиально

**Comment by mmarti42** [comment]
ls >&-1
*****************************************
token->value = |ls|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 0
token->end_pos = 3
*****************************************
*****************************************
token->value = NULL
token->type = GREATER
token->class = C_REDIR
token->start_pos = 3
token->end_pos = 4
*****************************************
*****************************************
token->value = |&-1|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 4
token->end_pos = 7
*****************************************
*****************************************
token->value = NULL
token->type = T_END
token->class = C_END
token->start_pos = 7
token->end_pos = 7
*****************************************

**Comment by mmarti42** [comment]
Если после токена GREATER_AND стоит минус, то минус идет в как часть токена GREATER_AND, а все остальное как часть токена ls
ls 1&>-1
*****************************************
token->value = |ls 1&|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 0
token->end_pos = 5
*****************************************
*****************************************
token->value = NULL
token->type = GREATER
token->class = C_REDIR
token->start_pos = 5
token->end_pos = 6
*****************************************
*****************************************
token->value = |-1|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 6
token->end_pos = 8
*****************************************
*****************************************
token->value = NULL
token->type = T_END
token->class = C_END
token->start_pos = 8
token->end_pos = 8
*****************************************

Должно быть:
ls 1&>-1
*****************************************
token->value = |ls 1|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 0
token->end_pos = 5
*****************************************
*****************************************
token->value = |1&>-|
token->type = GREATER_AND
token->class = C_REDIR
token->start_pos = 5
token->end_pos = 6
*****************************************
*****************************************
token->value = NULL
token->type = T_END
token->class = C_END
token->start_pos = 8
token->end_pos = 8
*****************************************

**Comment by mmarti42** [comment]
Лучше все таки разделить составляющие n1>&n2 на два токена n1>& и n2 потому, что в баше 1>&file 
и 1>& file одно и то же

**Comment by mmarti42** [comment]
в общем а >& надо переделать

ls >&
*****************************************
token->value = |ls|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 0
token->end_pos = 3
*****************************************
*****************************************
token->value = NULL
token->type = GREATER
token->class = C_REDIR
token->start_pos = 3
token->end_pos = 4
*****************************************
*****************************************
token->value = |&|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 4
token->end_pos = 5
*****************************************
*****************************************
token->value = NULL
token->type = T_END
token->class = C_END
token->start_pos = 5
token->end_pos = 5
*****************************************

**Comment by OlegMulko** [comment]
> и еще, если у нас есть T_END, то не нужен массив указателей, достаточно массива структур. Можно оставить так, можно переделать - на твое усмотрение

Хорошо, будет корректнее переделать просто под массив структур.

**Comment by OlegMulko** [comment]
> В токенах T_GREAT value = NULL, но в них может быть указан дескриптор, например "2>tmp.txt". То же самое с T_LESS, T_GREATER_GREATER, T_LESS_LESS. В общем везде нужно поле value

Как я понимаю значение дескриптора здесь может принимать значения только 0, 1 и 2?

**Comment by mmarti42** [comment]
> > В токенах T_GREAT value = NULL, но в них может быть указан дескриптор, например "2>tmp.txt". То же самое с T_LESS, T_GREATER_GREATER, T_LESS_LESS. В общем везде нужно поле value
> 
> Как я понимаю значение дескриптора здесь может принимать значения только 0, 1 и 2?

По посиксу 0-9

**Comment by OlegMulko** [comment]
> > > В токенах T_GREAT value = NULL, но в них может быть указан дескриптор, например "2>tmp.txt". То же самое с T_LESS, T_GREATER_GREATER, T_LESS_LESS. В общем везде нужно поле value
> > 
> > 
> > Как я понимаю значение дескриптора здесь может принимать значения только 0, 1 и 2?
> 
> По посиксу 0-9

Ок

**Comment by OlegMulko** [comment]
> Лучше все таки разделить составляющие n1>&n2 на два токена n1>& и n2 потому, что в баше 1>&file
> и 1>& file одно и то же

поправил формирование токена >&.
при таком варианте 1>&file
*****************************************
token->value = |1>&|
token->type = GREATER_AND
token->class = C_REDIR
token->start_pos = 3
token->end_pos = 6
*****************************************
*****************************************
token->value = |file|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 6
token->end_pos = 7
*****************************************
НО
при таком варианте 1>&file ls -1, будет
*****************************************
token->value = |1>&|
token->type = GREATER_AND
token->class = C_REDIR
token->start_pos = 3
token->end_pos = 6
*****************************************
*****************************************
token->value = |file ls -1|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 6
token->end_pos = 7
*****************************************

**Comment by OlegMulko** [comment]
> **Если число перед токеном перенаправления отрицательное, лексер воспринимает его, как аргумент:**
> ls -1>&1
> 
> token->value = |ls -|
> token->type = T_WORD
> token->class = C_WORD
> token->start_pos = 0
> token->end_pos = 4
> 
> token->value = |1>&1|
> token->type = GREATER_AND
> token->class = C_REDIR
> token->start_pos = 4
> token->end_pos = 8
> 
> token->value = NULL
> token->type = T_END
> token->class = C_END
> token->start_pos = 8
> token->end_pos = 8
> 
> **Должно быть:**
> ls -1>&1
> 
> token->value = |ls -1|
> token->type = T_WORD
> token->class = C_WORD
> token->start_pos = 0
> token->end_pos = 4
> 
> token->value = |>&1|
> token->type = GREATER_AND
> token->class = C_REDIR
> token->start_pos = 4
> token->end_pos = 8
> 
> token->value = NULL
> token->type = T_END
> token->class = C_END
> token->start_pos = 8
> token->end_pos = 8

Поправил!

**Comment by OlegMulko** [comment]
> > и еще, если у нас есть T_END, то не нужен массив указателей, достаточно массива структур. Можно оставить так, можно переделать - на твое усмотрение
> 
> Хорошо, будет корректнее переделать просто под массив структур.

Оставим первоначальный вариант с указателями!

**Comment by mmarti42** [comment]
ls > file ls
*****************************************
token->value = |ls|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 0
token->end_pos = 3
*****************************************
*****************************************
token->value = NULL
token->type = GREATER
token->class = C_REDIR
token->start_pos = 3
token->end_pos = 4
*****************************************
*****************************************
token->value = |file ls|
token->type = T_WORD
token->class = C_WORD
token->start_pos = 5
token->end_pos = 12
*****************************************
*****************************************
token->value = NULL
token->type = T_END
token->class = C_END
token->start_pos = 12
token->end_pos = 12
*****************************************

file и ls должны быть разными токенами. Видимо все-таки придется разделить все токены T_WORD по пробелам

**Comment by OlegMulko** [comment]
> ls > file ls
> 
> token->value = |ls|
> token->type = T_WORD
> token->class = C_WORD
> token->start_pos = 0
> token->end_pos = 3
> 
> token->value = NULL
> token->type = GREATER
> token->class = C_REDIR
> token->start_pos = 3
> token->end_pos = 4
> 
> token->value = |file ls|
> token->type = T_WORD
> token->class = C_WORD
> token->start_pos = 5
> token->end_pos = 12
> 
> token->value = NULL
> token->type = T_END
> token->class = C_END
> token->start_pos = 12
> token->end_pos = 12
> 
> file и ls должны быть разными токенами. Видимо все-таки придется разделить все токены T_WORD по пробелам

Вот это меня и смутило, поэтому и задал вопрос про разделение по пробелу. Сегодня поправлю!

**Comment by OlegMulko** [comment]
> ls > file ls
> 
> token->value = |ls|
> token->type = T_WORD
> token->class = C_WORD
> token->start_pos = 0
> token->end_pos = 3
> 
> token->value = NULL
> token->type = GREATER
> token->class = C_REDIR
> token->start_pos = 3
> token->end_pos = 4
> 
> token->value = |file ls|
> token->type = T_WORD
> token->class = C_WORD
> token->start_pos = 5
> token->end_pos = 12
> 
> token->value = NULL
> token->type = T_END
> token->class = C_END
> token->start_pos = 12
> token->end_pos = 12
> 
> file и ls должны быть разными токенами. Видимо все-таки придется разделить все токены T_WORD по пробелам

Поправил! теперь токены T_WORD нарезаются по пробелам
