### ISSUE TITLE
Invalid read

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#120]
**ls 1>&2**
==88780== Invalid read of size 1
==88780==    at 0x100010DDE: lex_is_asig_name (lex_asig_name.c:25)
==88780==    by 0x10001147C: lex_check_alnum (lex_check_tkn.c:39)
==88780==    by 0x1000123DF: lex_check_type (lex_tkn_type.c:25)
==88780==    by 0x100011C3B: lex_get_next_tkn (lex_get_tkn.c:45)
==88780==    by 0x100011FE6: lex_get_tkns (lex_lexer.c:39)
==88780==    by 0x10000DF47: check_valid_string (ft_term.c:67)
==88780==    by 0x10000DEE4: term_start (ft_term.c:54)
==88780==    by 0x10000DE18: main (ft_term.c:28)
==88780==  Address 0x104f3b338 is 0 bytes after a block of size 8 alloc'd
==88780==    at 0x1000BE626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==88780==    by 0x100012A54: ft_strdup (in ./42sh)
==88780==    by 0x10000BD52: ft_readline (rl_main.c:23)
==88780==    by 0x10000DEB9: term_start (ft_term.c:49)
==88780==    by 0x10000DE18: main (ft_term.c:28)
==88780== 
==88780== Invalid read of size 1
==88780==    at 0x100010DFD: lex_is_asig_name (lex_asig_name.c:25)
==88780==    by 0x10001147C: lex_check_alnum (lex_check_tkn.c:39)
==88780==    by 0x1000123DF: lex_check_type (lex_tkn_type.c:25)
==88780==    by 0x100011C3B: lex_get_next_tkn (lex_get_tkn.c:45)
==88780==    by 0x100011FE6: lex_get_tkns (lex_lexer.c:39)
==88780==    by 0x10000DF47: check_valid_string (ft_term.c:67)
==88780==    by 0x10000DEE4: term_start (ft_term.c:54)
==88780==    by 0x10000DE18: main (ft_term.c:28)
==88780==  Address 0x104f3b338 is 0 bytes after a block of size 8 alloc'd
==88780==    at 0x1000BE626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==88780==    by 0x100012A54: ft_strdup (in ./42sh)
==88780==    by 0x10000BD52: ft_readline (rl_main.c:23)
==88780==    by 0x10000DEB9: term_start (ft_term.c:49)
==88780==    by 0x10000DE18: main (ft_term.c:28)
==88780== 
==88780== Invalid read of size 1
==88780==    at 0x100010E35: lex_is_asig_name (lex_asig_name.c:27)
==88780==    by 0x10001147C: lex_check_alnum (lex_check_tkn.c:39)
==88780==    by 0x1000123DF: lex_check_type (lex_tkn_type.c:25)
==88780==    by 0x100011C3B: lex_get_next_tkn (lex_get_tkn.c:45)
==88780==    by 0x100011FE6: lex_get_tkns (lex_lexer.c:39)
==88780==    by 0x10000DF47: check_valid_string (ft_term.c:67)
==88780==    by 0x10000DEE4: term_start (ft_term.c:54)
==88780==    by 0x10000DE18: main (ft_term.c:28)
==88780==  Address 0x104f3b338 is 0 bytes after a block of size 8 alloc'd
==88780==    at 0x1000BE626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==88780==    by 0x100012A54: ft_strdup (in ./42sh)
==88780==    by 0x10000BD52: ft_readline (rl_main.c:23)
==88780==    by 0x10000DEB9: term_start (ft_term.c:49)
==88780==    by 0x10000DE18: main (ft_term.c:28)

**Comment by OlegMulko** [comment]
Поправил
