### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#147]
если в конце команды добавить один пробел вылетает сега

mmarti@oa-c5.21-school.ru:~/Desktop/42sh
$> ls 
zsh: segmentation fault  ./42sh

**Comment by mmarti42** [comment]
![5E6F0DF0-CBD1-414E-9F24-DD3F01DB1172](https://user-images.githubusercontent.com/50182477/71320411-f8361680-24bb-11ea-99b6-235645117c12.png)

Исправил таким образом. Никуда не пушил пока

**Comment by OlegMulko** [comment]
Ок, сегодня разберусь!

**Comment by OlegMulko** [comment]
Исправил! Поправил функцию t_lex_tkn_type	lex_check_end(char **str, short is_word, size_t *pos)

**Comment by OlegMulko** [comment]
OK!
