### ISSUE TITLE
Дополнение строки, если крайний токен &&, || или |

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#158]

**Comment by OlegMulko** [comment]
Ок, добавлю вызов readline как при кавычках!

**Comment by mmarti42** [comment]
Это, наверное, нужно сделать мне во время проверки на валидность

**Comment by mmarti42** [comment]
Напиши, пожалуйста, функцию, которая вызывает ридлайн, дополняет строку и дополняет список токенов и добавь ее в term/ft_term.c
Я оставил коммент в нужном месте.

**Comment by OlegMulko** [comment]
Готово
