### ISSUE TITLE
assignment word bug

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#161]
$> a=b;echo $a
*****************************************
token->value = |a=b;echo|
token->type = ASSIGNMENT_WORD
token->class = ASSIGNMENT_WORD
token->start_pos = 0
token->end_pos = 8

**Comment by OlegMulko** [comment]
Ок. Кстати думал над этим моментом, какие разделители кроме " " и ";" надо использовать?

**Comment by OlegMulko** [comment]
Поправил, пока добавил в качестве разделителя ";", надо подумать какие еще разделители добавить.

**Comment by mmarti42** [comment]
> Поправил, пока добавил в качестве разделителя ";", надо подумать какие еще разделители добавить

Такие же, как для токенов word

**Comment by mmarti42** [comment]
Я вообще собираюсь объединить word, assignment_word и все токены,которые заменяются на word в один класс для валидации.

**Comment by mmarti42** [comment]
Вообще классы нужно переработать
