### ISSUE TITLE
logical operators

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#195]
$> ls signal || pwd
Makefile	objs
includes	srcs
/Users/aashara-/Desktop/test
aashara- su-b2.21-school.ru ~/Desktop/test
$> ls tst && pwd
ls: tst: No such file or directory
/Users/aashara-/Desktop/test
aashara- su-b2.21-school.ru ~/Desktop/test
$>

**Comment by mmarti42** [comment]
Их должен сделать  Дима
