### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#200]
cd -r

==47676== 1,355 (272 direct, 1,083 indirect) bytes in 1 blocks are definitely lost in loss record 57 of 65
==47676==    at 0x1000C5626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==47676==    by 0x100018A2C: ft_dardup (in ./42sh)
==47676==    by 0x1000030AB: get_uniq_env (uniq_env.c:61)
==47676==    by 0x100002151: launch_builtin (launch_builtin.c:65)
==47676==    by 0x100002474: launch_job (launch_job.c:95)
==47676==    by 0x100007D6B: exec_jobs (exec_jobs.c:35)
==47676==    by 0x100012EE8: ft_system (ft_term.c:57)
==47676==    by 0x100012E54: term_start (ft_term.c:36)
==47676==    by 0x100012DF1: main (ft_term.c:20)
==47676==
==47676== 2,816 bytes in 44

**Comment by mmarti42** [comment]
fixed
