### ISSUE TITLE
Redir bug

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#202]
at-l6:42sh (master*) $ ./42sh
aashara- at-l6.21-school.ru ~/Desktop/42sh
$> echo 1 >out >&2 2>err
1
42sh: dup2() error

**Comment by mmarti42** [comment]
$> echo fsasdaf >1
$> echo fsasdaf >1
$> echo fsasdaf >1
$> echo fsasdaf >1
$> lsof -c 42sh
COMMAND  PID   USER   FD   TYPE             DEVICE  SIZE/OFF     NODE NAME
42sh    2101 mmarti  cwd    DIR                1,9       884  2194106 /Users/mmarti/Desktop/master
42sh    2101 mmarti  txt    REG                1,9    188532  2206991 /Users/mmarti/Desktop/master/42sh
42sh    2101 mmarti  txt    REG                1,7    698896 12345479 /usr/lib/dyld
42sh    2101 mmarti  txt    REG                1,7 663060480 12581739 /private/var/db/dyld/dyld_shared_cache_x86_64h
42sh    2101 mmarti    0u   CHR               16,2   0t19280     4001 /dev/ttys002
42sh    2101 mmarti    1u   CHR               16,2   0t19280     4001 /dev/ttys002
42sh    2101 mmarti    2u   CHR               16,2   0t19280     4001 /dev/ttys002
42sh    2101 mmarti    **3u   REG                1,9         8  2208182 /Users/mmarti/Desktop/master/1**
42sh    2101 mmarti    **4u   REG                1,9         8  2208182 /Users/mmarti/Desktop/master/1**
42sh    2101 mmarti    5u  unix 0xd002dcbd06c9f527       0t0          ->0xd002dcbd01196e8f
42sh    2101 mmarti    **6u   REG                1,9         8  2208182 /Users/mmarti/Desktop/master/1**
42sh    2101 mmarti    **7u   REG                1,9         8  2208182 /Users/mmarti/Desktop/master/1**

Кое-кто не закрывает дескрипторы это не мой косяк

**Comment by HumanBean17** [comment]
Дескрипторы закрываются, но проблема остается

**Comment by mmarti42** [comment]
fixed
