### ISSUE TITLE
Pipe bug

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#203]
$> exit 1 | exit 2 | exit 3; echo "stayin' alive"
42sh: tcssetattr() error
42sh: tcssetattr() error
42sh(51605,0x7fffc54d13c0) malloc: *** error for object 0x7f96c60001b0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by mmarti42** [comment]
И это тоже не мой косяк
