### ISSUE TITLE
type invalid read

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#205]
aashara- at-p5.21-school.ru ~/Desktop/new_42sh
$> type ls
==71300== Invalid read of size 1
==71300==    at 0x1000173E5: ft_strlen (in ./42sh)
==71300==    by 0x10001916F: ft_pathjoin (in ./42sh)
==71300==    by 0x100010CF1: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==  Address 0x100e88cad is 701 bytes inside a block of size 4,096 free'd
==71300==    at 0x1000B8A03: free (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002E7A11: closedir (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010CD7: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==  Block was alloc'd at
==71300==    at 0x1000B8626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002EE1AB: __opendir_common (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010C76: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300== 
==71300== Invalid read of size 1
==71300==    at 0x1000191F9: ft_pathjoin (in ./42sh)
==71300==    by 0x100010CF1: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==    by 0x100001757: main (in ./42sh)
==71300==  Address 0x100e88cad is 701 bytes inside a block of size 4,096 free'd
==71300==    at 0x1000B8A03: free (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002E7A11: closedir (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010CD7: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==  Block was alloc'd at
==71300==    at 0x1000B8626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002EE1AB: __opendir_common (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010C76: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300== 
==71300== Invalid read of size 1
==71300==    at 0x100019225: ft_pathjoin (in ./42sh)
==71300==    by 0x100010CF1: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==    by 0x100001757: main (in ./42sh)
==71300==  Address 0x100e88cad is 701 bytes inside a block of size 4,096 free'd
==71300==    at 0x1000B8A03: free (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002E7A11: closedir (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010CD7: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==  Block was alloc'd at
==71300==    at 0x1000B8626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002EE1AB: __opendir_common (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010C76: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300== 
==71300== Invalid read of size 1
==71300==    at 0x10001923D: ft_pathjoin (in ./42sh)
==71300==    by 0x100010CF1: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==    by 0x100001757: main (in ./42sh)
==71300==  Address 0x100e88cad is 701 bytes inside a block of size 4,096 free'd
==71300==    at 0x1000B8A03: free (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002E7A11: closedir (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010CD7: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300==  Block was alloc'd at
==71300==    at 0x1000B8626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71300==    by 0x1002EE1AB: __opendir_common (in /usr/lib/system/libsystem_c.dylib)
==71300==    by 0x100010C76: locate (in ./42sh)
==71300==    by 0x100010BED: find_in_path (in ./42sh)
==71300==    by 0x1000172BB: get_fname_type (in ./42sh)
==71300==    by 0x100017154: isfile (in ./42sh)
==71300==    by 0x1000170CA: ft_type (in ./42sh)
==71300==    by 0x100011826: launch_builtin (in ./42sh)
==71300==    by 0x100011B27: launch_job (in ./42sh)
==71300==    by 0x1000104E0: exec_jobs (in ./42sh)
==71300==    by 0x10000170E: ft_system (in ./42sh)
==71300==    by 0x10000186D: shell_start (in ./42sh)
==71300== 
ls is /bin/ls

**Comment by mmarti42** [comment]
fixed
