### ISSUE TITLE
Unique environment for builtins

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#206]
В общем нужно переделать все билт ины (кто какие делал) под прототип:

int func(int argc, char **argv, char **environ)

Если билт ин использует переменную окружения, то берёт он ее из environ, который в прототипе. Запись идёт как обычно в глобальный массив переменных окружения

**Comment by fica99** [comment]
Сегодня сделаю

**Comment by fica99** [comment]
То есть если мой билтин использует переменные окружения, то get_var не подойдет? Мне надо напрямую искать в 3 аргументе?

**Comment by fica99** [comment]
Можете использовать  `char		*ft_getvar(char *name, char **varlist)`

**Comment by fica99** [comment]
Сделано, все остальные сделайте тоже самое на ветке 206_Unique_environment_for_builtins

**Comment by Kugumi** [comment]
Сделала для echo, type, test
