### ISSUE TITLE
tmp variable

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#213]
aashara- at-p6.21-school.ru ~/Desktop/42sh
$> HOME=$HOME/Desktop cd
42sh: cd: $HOME/Desktop: no such file or directory
aashara- at-p6.21-school.ru ~/Desktop/42sh
$> pwd
/Users/aashara-/Desktop/42sh
aashara- at-p6.21-school.ru ~/Desktop/42sh
$>

**Comment by mmarti42** [comment]
spec_symb("var=$HOME/Desktop") must return "var=/Users/jijerde/Desktop"
