### ISSUE TITLE
variable bug

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#247]
aashara- at-a2.21-school.ru ~/Desktop/test
$> a=hello b=world; b=42 echo $a_$b && echo $b
aashara- at-a2.21-school.ru ~/Desktop/test
$>

**Comment by fica99** [comment]
Our shell:
aashara- at-a2.21-school.ru ~/Desktop/test
$> echo "$PWD
> "

aashara- at-a2.21-school.ru ~/Desktop/test
$>


bash:

bash-3.2$ echo "$PWD
> "
/Users/aashara-

**Comment by fica99** [comment]
our shell:

aashara- at-a1.21-school.ru ~/Desktop/test
$> a=hello b=world
aashara- at-a1.21-school.ru ~/Desktop/test
$> set
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.kyf2Tvl8iW/Render
COLORTERM=truecolor
COMMAND_MODE=unix2003
HOME=/Users/aashara-
HOMEBREW_CACHE=/tmp/aashara-/Homebrew/Caches
HOMEBREW_TEMP=/tmp/aashara-/Homebrew/Temp
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS=-R
LOGNAME=aashara-
LSCOLORS=Gxfxcxdxbxegedabagacad
OLDPWD=/Users/aashara-/Desktop/test
PAGER=less
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/munki:/Users/aashara-/.brew/bin
PWD=/Users/aashara-/Desktop/test
SECURITYSESSIONID=186ea
SHELL=/bin/zsh
SHLVL=2
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.JuH42CNj2p/Listeners
TERM=xterm-256color
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.37.1
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n0000ykh0007mm/T/
USER=aashara-
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=/Users/aashara-/.oh-my-zsh
__CF_USER_TEXT_ENCODING=0x1E94:0x0:0x0
?=0
PS1=\u \H \w
\$> 
PS2=> 
READMODE=EMACS
HISTFILE=/Users/aashara-/.42sh_history
HISTSIZE=500
HISTFILESIZE=500
a=hello

bash:

bash-3.2$ a=hello b=world
bash-3.2$ set
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.kyf2Tvl8iW/Render
BASH=/bin/bash
BASH_ARGC=()
BASH_ARGV=()
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="3" [1]="2" [2]="57" [3]="1" [4]="release" [5]="x86_64-apple-darwin16")
BASH_VERSION='3.2.57(1)-release'
COLORTERM=truecolor
COLUMNS=153
COMMAND_MODE=unix2003
DIRSTACK=()
EUID=7828
GROUPS=()
HISTFILE=/Users/aashara-/.bash_history
HISTFILESIZE=500
HISTSIZE=500
HOME=/Users/aashara-
HOMEBREW_CACHE=/tmp/aashara-/Homebrew/Caches
HOMEBREW_TEMP=/tmp/aashara-/Homebrew/Temp
HOSTNAME=at-a1.21-school.ru
HOSTTYPE=x86_64
IFS=$' \t\n'
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS=-R
LINES=24
LOGNAME=aashara-
LSCOLORS=Gxfxcxdxbxegedabagacad
MACHTYPE=x86_64-apple-darwin16
MAILCHECK=60
OPTERR=1
OPTIND=1
OSTYPE=darwin16
PAGER=less
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/munki:/Users/aashara-/.brew/bin
PIPESTATUS=([0]="0")
PPID=46934
PS1='\s-\v\$ '
PS2='> '
PS4='+ '
PWD=/Users/aashara-/Desktop/test
SECURITYSESSIONID=186ea
SHELL=/bin/zsh
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
SHLVL=3
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.JuH42CNj2p/Listeners
TERM=xterm-256color
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.37.1
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n0000ykh0007mm/T/
UID=7828
USER=aashara-
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=/Users/aashara-/.oh-my-zsh
_=
__CF_USER_TEXT_ENCODING=0x1E94:0x0:0x0
a=hello
b=world

**Comment by fica99** [comment]
aashara- at-a2.21-school.ru ~/Desktop/test
$> directory=/ ls_opt=-atr
aashara- at-a2.21-school.ru ~/Desktop/test
$> ls $ls_opt $directory
ls: fts_open: No such file or directory
aashara- at-a2.21-school.ru ~/Desktop/test

**Comment by mmarti42** [comment]
fixed
