### ISSUE TITLE
Memory errors with tilda expressions

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#25]
Memory error with expression `ls ~`

$> ls ~
==27066== Invalid write of size 1
==27066==    at 0x1121E7: ft_strcat (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x1133D5: ft_stradd (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B82A: tilda_expr (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B762: spec_symbols (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A4F1: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066==  Address 0x58374a3 is 0 bytes after a block of size 3 alloc'd
==27066==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27066==    by 0x113084: ft_memalloc (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x11273B: ft_strsub (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x112AA6: ft_strsplit (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A485: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066== 
==27066== Invalid write of size 1
==27066==    at 0x112212: ft_strcat (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x1133D5: ft_stradd (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B82A: tilda_expr (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B762: spec_symbols (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A4F1: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066==  Address 0x58374ad is 10 bytes after a block of size 3 alloc'd
==27066==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27066==    by 0x113084: ft_memalloc (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x11273B: ft_strsub (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x112AA6: ft_strsplit (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A485: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066== 
==27066== Invalid read of size 1
==27066==    at 0x11226F: ft_strchr (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B777: spec_symbols (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A4F1: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066==  Address 0x58374a3 is 0 bytes after a block of size 3 alloc'd
==27066==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27066==    by 0x113084: ft_memalloc (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x11273B: ft_strsub (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x112AA6: ft_strsplit (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A485: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066== 
==27066== Invalid read of size 1
==27066==    at 0x112244: ft_strchr (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B777: spec_symbols (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A4F1: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066==  Address 0x58374a3 is 0 bytes after a block of size 3 alloc'd
==27066==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27066==    by 0x113084: ft_memalloc (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x11273B: ft_strsub (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x112AA6: ft_strsplit (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A485: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066== 
==27066== Invalid read of size 1
==27066==    at 0x11226F: ft_strchr (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B79F: spec_symbols (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A4F1: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066==  Address 0x58374a3 is 0 bytes after a block of size 3 alloc'd
==27066==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27066==    by 0x113084: ft_memalloc (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x11273B: ft_strsub (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x112AA6: ft_strsplit (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A485: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066== 
==27066== Invalid read of size 1
==27066==    at 0x112244: ft_strchr (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B79F: spec_symbols (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A4F1: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066==  Address 0x58374a3 is 0 bytes after a block of size 3 alloc'd
==27066==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27066==    by 0x113084: ft_memalloc (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x11273B: ft_strsub (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x112AA6: ft_strsplit (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10A485: make_command (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27066==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27066== 
==27067== Syscall param execve(argv[i]) points to unaddressable byte(s)
==27067==    at 0x514AE37: execve (syscall-template.S:78)
==27067==    by 0x10A93F: check_bin (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x10A6F5: find_command (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x10A527: make_command (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)
==27067==  Address 0x58374a3 is 0 bytes after a block of size 3 alloc'd
==27067==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==27067==    by 0x113084: ft_memalloc (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x11273B: ft_strsub (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x112AA6: ft_strsplit (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x10A485: make_command (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x10B1D6: interpret_ast (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x111E3B: check_valid_string (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x111D9D: term_start (in /home/aashara/projects/42sh/42sh)
==27067==    by 0x111D31: main (in /home/aashara/projects/42sh/42sh)

**Comment by mmarti42** [comment]
solved
