### ISSUE TITLE
echo prompt

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#252]
Our shell:
aashara- at-a2.21-school.ru ~/Desktop/test
$> echo "\\'abcd\\'"
'abcd'

bash:
bash-3.2$  echo "\\'abcd\\'"
\\'abcd\\'

**Comment by OlegMulko** [comment]
OK!

**Comment by OlegMulko** [comment]
work work ~/projects/42sh
$> echo "\'abcd\'"
*****************************************
token->value = |echo|
token->type = WORD
token->class = WORD
token->start_pos = 0
token->end_pos = 4
*****************************************
*****************************************
token->value = |\'abcd\'|
token->type = WORD
token->class = WORD
token->start_pos = 5
token->end_pos = 15
*****************************************
*****************************************
token->value = ||
token->type = END
token->class = END
token->start_pos = 15
token->end_pos = 16
*****************************************
