### ISSUE TITLE
pipe(?) bug

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#258]
mmarti mi-e3.21-school.ru ~/Desktop/42sh
$> base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g
       No
base64 killed by signal 13

**Comment by HumanBean17** [comment]
base64 /dev/urandom | head -c 10
Падает даже на простом тесте
Проблема всегда была, просто стала заметна только как я добавил вывод. Хотя вывод такой какой и должен быть, пайпы работают вроде правильно

**Comment by fica99** [comment]
aashara aashara ~/projects/42sh
$> base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g
Sigpipe: 13
Sigpipe: 13
No
aashara aashara ~/projects/42sh
$> base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g
Sigpipe: 13
No
aashara aashara ~/projects/42sh
$> base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g
Sigpipe: 13
No
aashara aashara ~/projects/42sh
$> base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g
Sigpipe: 13
No
aashara aashara ~/projects/42sh
$>

**Comment by fica99** [comment]
aashara aashara ~/projects/42sh
$> base64 /dev/urandom | head -c 10
qGR0KiL0xoSigpipe: 13
aashara aashara ~/projects/42sh
$> base64 /dev/urandom | head -c 10
yR1rFF2Bo3aashara aashara ~/projects/42sh
$> base64 /dev/urandom | head -c 10
1v7lTI5HeRaashara aashara ~/projects/42sh
$> base64 /dev/urandom | head -c 10
wWC3LLxxxYaashara aashara ~/projects/42sh
$> base64 /dev/urandom | head -c 10
mQiNRwqWvSSigpipe: 13
aashara aashara ~/projects/42sh
$>
