### ISSUE TITLE
PATH env bug

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#262]
aashara- at-a2.21-school.ru ~/Desktop/test
$> unset PATH
aashara- at-a2.21-school.ru ~/Desktop/test
$> ;s
42sh: command not found: s
aashara- at-a2.21-school.ru ~/Desktop/test
$> ls
42sh: command not found: ls
aashara- at-a2.21-school.ru ~/Desktop/test
$> fertg
42sh: command not found: fertg
aashara- at-a2.21-school.ru ~/Desktop/test
$> gre
42sh: command not found: gre
aashara- at-a2.21-school.ru ~/Desktop/test
$> fg
aashara- at-a2.21-school.ru ~/Desktop/test
$> q
42sh: command not found: q
aashara- at-a2.21-school.ru ~/Desktop/test
$> w
42sh: command not found: w
aashara- at-a2.21-school.ru ~/Desktop/test
$> e
42sh: command not found: e
aashara- at-a2.21-school.ru ~/Desktop/test
$> gertg
42sh: command not found: gertg
aashara- at-a2.21-school.ru ~/Desktop/test
$> PATH=/bin:/usr/bin
aashara- at-a2.21-school.ru ~/Desktop/test
$> mkdir testdir
42sh: command not found: mkdir

**Comment by mmarti42** [comment]
fixed

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru /private
$> unset PATH
aashara- at-a1.21-school.ru /private
$> PATH=/bin:/usr/bin
aashara- at-a1.21-school.ru /private
$> mkdir testdir
mkdir: testdir: Permission denied
aashara- at-a1.21-school.ru /private
$> type mkdir
42sh: type: mkdir: not found
aashara- at-a1.21-school.ru /private
$>

**Comment by fica99** [comment]
aashara aashara ~/projects/42sh
$>  unset PATH
aashara aashara ~/projects/42sh
$> PATH=/bin:/usr/bin
aashara aashara ~/projects/42sh
$> type mkdir
42sh: type: mkdir: not found
aashara aashara ~/projects/42sh
$> mkdir se
aashara aashara ~/projects/42sh
$> type mkdir
42sh: type: mkdir: not found
aashara aashara ~/projects/42sh
$>

**Comment by fica99** [comment]
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> unset PATH
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> ;s
> 42sh: command not found: s
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> ls
> 42sh: command not found: ls
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> fertg
> 42sh: command not found: fertg
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> gre
> 42sh: command not found: gre
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> fg
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> q
> 42sh: command not found: q
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> w
> 42sh: command not found: w
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> e
> 42sh: command not found: e
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> gertg
> 42sh: command not found: gertg
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> PATH=/bin:/usr/bin
> aashara- at-a2.21-school.ru ~/Desktop/test
> $> mkdir testdir
> 42sh: command not found: mkdir

FIXED

**Comment by mmarti42** [comment]
fixed
