### ISSUE TITLE
error with big command

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#269]
aashara- at-a2.21-school.ru ~/Desktop/test
$> cat ~/.42sh_historycat ~/.42sh_history/bin/ls/bin/ls(echo c; ())(echo c; ())(echo c; ()
)(; echo b) echo "\'abcd\'"echo 'echo "\'abcd\'"catcatpython -c 'import os, signal;os.kill
(os.getpid(), signal.SIGSEGV)'ps a | grep "ls -Rl /" | grep -v 'grep'jobsps a | grep "ls -
Rl /" | grep -v 'grep' | cut -d ' ' -f 1kill 16057kill 1607ps a | grep "ls -Rl /" | grep -
v 'grep' | cut -d ' ' -f 1ps a | grep "ls -Rl /" ps a | grep "ls -Rl /" | grep -v 'grep' |
 cut -d ' ' -f 2ps a | grep "ls -Rl /" | grep -v 'grep' ps a | grep "ls -Rl /" ps a | grep
 "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2ps a | grep "ls -Rl /" | grep -v 'grep' | cu
t -d ' ' -f 2ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2psjobsps a | grep "l
s -Rl /" | grep -v 'grep' | cut -d ' ' -f 2jobsls -Rl / 2>&1jobscat -ejobsfg 6fg 9jobsfg 9
fg 8fg 7jobsfg 6jobsfg 10jobsemacs -nw &emacs -nw &emacs -nw &emacs -nw &emacs -nw &jobs l
s -lR /usr >fifo 2>&1 &mkfifo fifotrue; echo $?; false; echo $?true; echo $?; false; echo
$?mkdir testdirPATH=/bin:/usr/bingertgewqfggrefertgls;sunset PATHset | grep -E '(a|b)='env
 | grep -E '(a|b)=' unset a bONESHOT= env | grep ONESHOT printenv bexport benv | grep -E '
(a|b)='env | grep -E '(a|b)='envset | grep -E '(a|b)='b=worda=helloa= helloset | grep -E '
(a|b)='setecho $empty|cat -eecho $empty |cat -els $ls_opt $directorydirectory=/ ls_opt=-at
rtrue || echo foo && echo bar false && echo foo || echo barecho $? ls doesnotexist || echo
 "Notice me senpai" ls -l && lspwdcd -cd /tmp/aashara-echo $? exit 1 2 3echo $? exit 1 2 3
cat /tmp/heredoc-appendcat -e >> /tmp/heredoc-append << FINcat > /tmp/heredoc-append << FI
Ncat << EOFcat << ENDecho out >&-; echo out2 exit 1 | exit 2 | exit 3; echo "stayin' alive
"ls -1; touch test_file; ls -1ls -1; touch test_file; ls -1 base64 < /dev/urandom | head -
c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g base64 < /dev/urandom | head -c 10
00 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gls | sort -rn | cat -els doesnotexist .
 >/dev/null 2>&1ls doesnotexist . 2>&1 >/dev/nullcat <&- abccat redir_one_to_allcat 9 abcc
at 9 abvecho abc >redir_one_to_allcat <&4cat outcat errecho 2 >out 2>errecho 1 >out >&2 2>
err cat /tmp/ftsh_ls_out< /tmp/ftsh_ls_out cat -e >> /tmp/ftsh_ls_out cat /tmp/ftsh_ls_out
ls > /tmp/ftsh_ls_out / echo $?/bin/ls -l -a -F echo $? /bin/ls -alF echo $?/bin/ls echo $
?ewrgwerg echo $?/sbin/rgewrgerw echo $? echo ${?} echo ${PWD}tgertgrepwdHOME=$HOME/Deskto
p cda=hello b=world; b=42 echo $a $ba=hello b=world; b=42 echo $a_$ba=hello b=world; b=42
echo $a_$ba=hello b=world; b=42 echo $a_$b && echo $bONESHOT= env | grep ONESHOTONESHOT=en
v | grep ONESHOTONESHOT= env | grep ONESHOTb"echo "$PWDaalias a="ls -la"aals gretals -laaa
lias a="ls -la"lslsbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes
/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e
 s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/
No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gb
ase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64
 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /d
ev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/ur
andom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g"echo "$PWDlslslsecho
 "'abcd'""echo "$PWDaaalias a="ls -l"ls"echo "$PWDecho "$PWD"ONESHOT= env | grep ONESHOTen
v | grep ONESHOT ONESHOT=env | grep ONESHOT ONESHOT= env | grep ONESHOT ps a | grep "ls -R
l /" | grep -v 'grep'ls -Rl / 2>&1cat -e 2jobscat -ejobsfg 4jobsemacs -nw &emacs -nw &emac
s -nw &emacs -nw &emacs -nw &jobsls -lR /usr >fifo 2>&1 &mkfifo fifols -lR /usr >fifo 2>&1
 &mkfifo fifopython -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'python -c '
import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'python -c 'import os, signal;os.kil
l(os.getpid(), signal.SIGSEGV)'catecho "\'abcd\'"echo 'echo "\'abcd\'"aaalias =lsalias a=l
slslsls!!!lslsabc=defalias ==lsalias =lsaalias a=lsaliasalias ==lsalias =lslsalias =lspwls
=alias =lsalias ==lsalias /=lslsecho << EOFps a | grep "ls -Rl /" | grep -v 'grep' | cut -
d ' ' -f 2ls -Rl / 2>&1" ls;echo "cd;pwdls doesnotexist || echo "Notice me senpai" ls;echo
 "cd;pwd"exit 1 | exit 2 | exit 3; echo "stayin' alive"cata=hello b=world; b=42 echo $a_$b
 && echo $ba=hello b=world; b=42 echo $a_$b && echo ${b}a=hello b=world; b=42 echo ${a}_${
b} && echo ${b}true || echo foo && echo bar false && echo foo || echo barecho 'No error' |
| echo 'You cant see me'ls doesnotexist || echo "Notice me senpai"ls -l && lstype type lsp
wdPWDcd -L /tmp; cd -P ..pwdcd -pwdcd /binpwdcd /tmp/bin/pwdcd/bin/pwdcd /tmpcd /Users/boc
al/Downlcd /Users/bocal/Downloads/frewrgcd /Users/bocal/Downloads/cd -pwdcd ../testing/tes
t_filesexit a b ccat << EOFcat << ENDcat << ENDcat << ENDcat << ENDecho out >&- || echo ou
t2echo out >&- || echo out2echo out >&- || echo out2echo out >&- && echo out2echo out >&-
| echo out2echo out >&-; echo out2ls;echo "cd;pwd"ls -1; touch test_file; ls -1base64 < /d
ev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/ur
andom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom
 | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g ls | sort -rn | cat -els
doesnotexist . >/dev/null 2>&1ls doesnotexist . 2>&1 >/dev/nullcat <&- abccat 9 abccat red
ir_one_to_all echo abc >redir_one_to_allcat <&4cat 6cat dup_fdcat 4echo 6> dup_fdcat outca
t errecho 2 >out 2>errecho 1 >out >&2 2>errcat /tmp/ftsh_ls_out< /tmp/ftsh_ls_out cat -e >
> /tmp/ftsh_ls_outcat /tmp/ftsh_ls_outls > /tmp/ftsh_ls_out /git statusecho $?/bin/ls -laF
echo $?/bin/ls -l -a -Fecho $?/bin/lsecho $?/sbin/ewfreecho $?echo $?doesnotexistlsecho $?
echo $?cd -echo $?cd ..echo $?cdc .echo $?echo $?ls ertgreecho $?pwd;pwdlslsldlsfcfcfclsgi
t statusfcpwdlsldfc 500lsREADMODE=VIsetls;\pwdls;ls;\pwdls;ls\;pwdlsls;\pwdpwdlsaalias a=l
slsunalias -aunalias p -aaliasunalias a p saliasunaliasunalias calias p l s w calias peali
as ealiasalias e=echoalias c=cdalias p=pwdalias l=ls
cat ~/.42sh_historycat ~/.42sh_history/bin/ls/bin/ls(echo c; ())(echo c; ())(echo c; ())(; echo b) echo "\'abcd\'"echo 'echo "\'abcd\'"catcatpython -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'ps a | grep "ls -Rl /" | grep -v 'grep'jobsps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 1kill 16057kill 1607ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 1ps a | grep "ls -Rl /" ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2ps a | grep "ls -Rl /" | grep -v 'grep' ps a | grep "ls -Rl /" ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2ps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2psjobsps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2jobsls -Rl / 2>&1jobscat -ejobsfg 6fg 9jobsfg 9fg 8fg 7jobsfg 6jobsfg 10jobsemacs -nw &emacs -nw &emacs -nw &emacs -nw &emacs -nw &jobs ls -lR /usr >fifo 2>&1 &mkfifo fifotrue; echo $?; false; echo $?true; echo $?; false; echo $?mkdir testdirPATH=/bin:/usr/bingertgewqfggrefertgls;sunset PATHset | grep -E '(a|b)='env | grep -E '(a|b)=' unset a bONESHOT= env | grep ONESHOT printenv bexport benv | grep -E '(a|b)='env | grep -E '(a|b)='envset | grep -E '(a|b)='b=worda=helloa= helloset | grep -E '(a|b)='setecho $empty|cat -eecho $empty |cat -els $ls_opt $directorydirectory=/ ls_opt=-atrtrue || echo foo && echo bar false && echo foo || echo barecho $? ls doesnotexist || echo "Notice me senpai" ls -l && lspwdcd -cd /tmp/aashara-echo $? exit 1 2 3echo $? exit 1 2 3cat /tmp/heredoc-appendcat -e >> /tmp/heredoc-append << FINcat > /tmp/heredoc-append << FINcat << EOFcat << ENDecho out >&-; echo out2 exit 1 | exit 2 | exit 3; echo "stayin' alive"ls -1; touch test_file; ls -1ls -1; touch test_file; ls -1 base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gls | sort -rn | cat -els doesnotexist . >/dev/null 2>&1ls doesnotexist . 2>&1 >/dev/nullcat <&- abccat redir_one_to_allcat 9 abccat 9 abvecho abc >redir_one_to_allcat <&4cat outcat errecho 2 >out 2>errecho 1 >out >&2 2>err cat /tmp/ftsh_ls_out< /tmp/ftsh_ls_out cat -e >> /tmp/ftsh_ls_out cat /tmp/ftsh_ls_outls > /tmp/ftsh_ls_out / echo $?/bin/ls -l -a -F echo $? /bin/ls -alF echo $?/bin/ls echo $?ewrgwerg echo $?/sbin/rgewrgerw echo $? echo ${?} echo ${PWD}tgertgrepwdHOME=$HOME/Desktop cda=hello b=world; b=42 echo $a $ba=hello b=world; b=42 echo $a_$ba=hello b=world; b=42 echo $a_$ba=hello b=world; b=42 echo $a_$b && echo $bONESHOT= env | grep ONESHOTONESHOT=env | grep ONESHOTONESHOT= env | grep ONESHOTb"echo "$PWDaalias a="ls -la"aals gretals -laaalias a="ls -la"lslsbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g"echo "$PWDlslslsecho "'abcd'""echo "$PWDaaalias a="ls -l"ls"echo "$PWDecho "$PWD"ONESHOT= env | grep ONESHOTenv | grep ONESHOT ONESHOT=env | grep ONESHOT ONESHOT= env | grep ONESHOT ps a | grep "ls -Rl /" | grep -v 'grep'ls -Rl / 2>&1cat -e 2jobscat -ejobsfg 4jobsemacs -nw &emacs -nw &emacs -nw &emacs -nw &emacs -nw &jobsls -lR /usr >fifo 2>&1 &mkfifo fifols -lR /usr >fifo 2>&1 &mkfifo fifopython -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'python -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'python -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'catecho "\'abcd\'"echo 'echo "\'abcd\'"aaalias =lsalias a=lslslsls!=defalias ==lsalias =lsaalias a=lsaliasalias ==lsalias =lslsalias =lspwls=alias =lsalias ==lsalias /=lslsecho << EOFps a | grep "ls -Rl /" | grep -v 'grep' | cut -d ' ' -f 2ls -Rl / 2>&1" ls;echo "cd;pwdls doesnotexist || echo "Notice me senpai" ls;echo "cd;pwd"exit 1 | exit 2 | exit 3; echo "stayin' alive"cata=hello b=world; b=42 echo $a_$b && echo $ba=hello b=world; b=42 echo $a_$b && echo ${b}a=hello b=world; b=42 echo ${a}_${b} && echo ${b}true || echo foo && echo bar false && echo foo || echo barecho 'No error' || echo 'You cant see me'ls doesnotexist || echo "Notice me senpai"ls -l && lstype type lspwdPWDcd -L /tmp; cd -P ..pwdcd -pwdcd /binpwdcd /tmp/bin/pwdcd/bin/pwdcd /tmpcd /Users/bocal/Downlcd /Users/bocal/Downloads/frewrgcd /Users/bocal/Downloads/cd -pwdcd ../testing/test_filesexit a b ccat << EOFcat << ENDcat << ENDcat << ENDcat << ENDecho out >&- || echo out2echo out >&- || echo out2echo out >&- || echo out2echo out >&- && echo out2echo out >&- | echo out2echo out >&-; echo out2ls;echo "cd;pwd"ls -1; touch test_file; ls -1base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/gbase64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g ls | sort -rn | cat -els doesnotexist . >/dev/null 2>&1ls doesnotexist . 2>&1 >/dev/nullcat <&- abccat 9 abccat redir_one_to_all echo abc >redir_one_to_allcat <&4cat 6cat dup_fdcat 4echo 6> dup_fdcat outcat errecho 2 >out 2>errecho 1 >out >&2 2>errcat /tmp/ftsh_ls_out< /tmp/ftsh_ls_out cat -e >> /tmp/ftsh_ls_outcat /tmp/ftsh_ls_outls > /tmp/ftsh_ls_out /git statusecho $?/bin/ls -laFecho $?/bin/ls -l -a -Fecho $?/bin/lsecho $?/sbin/ewfreecho $?echo $?doesnotexistlsecho $?echo $?cd -echo $?cd ..echo $?cdc .echo $?echo $?ls ertgreecho $?pwd;pwdlslsldlsfcfcfclsgit statusfcpwdlsldfc 500lsREADMODE=VIsetls;\pwdls;ls;\pwdls;ls\;pwdlsls;\pwdpwdlsaalias a=lslsunalias -aunalias p -aaliasunalias a p saliasunaliasunalias calias p l s w calias pealias ealiasalias e=echoalias c=cdalias p=pwdalias l=ls
aashara- at-a2.21-school.ru ~/Desktop/test
$>

**Comment by mmarti42** [comment]
done
