### ISSUE TITLE
invalid malloc

### ISSUE THREAD

**Issue by mmarti42** [fica99/42sh#289]
mmarti at-b2.21-school.ru ~/Desktop/42sh
$> alias
alias l='ls�'

**Comment by mmarti42** [comment]
mmarti at-b2.21-school.ru ~/Desktop/42sh
$> alias aaa=bbb
==5170== Invalid write of size 1
==5170==    at 0x10000C9C3: lex_an_cut_quotes (lex_asig_name2.c:29)
==5170==    by 0x1000109DA: lex_parse_tkn_value (lex_val_tkn_processing.c:60)
==5170==    by 0x10000EFC7: lex_fill_value_pos (lex_get_tkn.c:59)
==5170==    by 0x10000EF5C: lex_get_next_tkn (lex_get_tkn.c:48)
==5170==    by 0x10000F466: lex_get_tkns (lex_lexer.c:39)
==5170==    by 0x100002164: ft_system (main.c:39)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==    by 0x100002217: main (main.c:72)
==5170==  Address 0x100e098e6 is 0 bytes after a block of size 6 alloc'd
==5170==    at 0x1000CB626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==5170==    by 0x10001AF50: ft_strnew (in ./42sh)
==5170==    by 0x10000C92C: lex_an_cut_quotes (lex_asig_name2.c:22)
==5170==    by 0x1000109DA: lex_parse_tkn_value (lex_val_tkn_processing.c:60)
==5170==    by 0x10000EFC7: lex_fill_value_pos (lex_get_tkn.c:59)
==5170==    by 0x10000EF5C: lex_get_next_tkn (lex_get_tkn.c:48)
==5170==    by 0x10000F466: lex_get_tkns (lex_lexer.c:39)
==5170==    by 0x100002164: ft_system (main.c:39)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==    by 0x100002217: main (main.c:72)
==5170== 
==5170== Invalid read of size 1
==5170==    at 0x10001A345: ft_strlen (in ./42sh)
==5170==    by 0x10001A394: ft_strdup (in ./42sh)
==5170==    by 0x100011A16: parse_word (word_list.c:34)
==5170==    by 0x100011821: word_list (word_list.c:118)
==5170==    by 0x100011A3A: parse_word (word_list.c:35)
==5170==    by 0x100011821: word_list (word_list.c:118)
==5170==    by 0x100011501: parse_ass_words (parse.c:20)
==5170==    by 0x100011410: parse_pipe (parse.c:26)
==5170==    by 0x10001132C: parse_logical (parse.c:39)
==5170==    by 0x100011278: parse (parse.c:50)
==5170==    by 0x1000021C6: ft_system (main.c:46)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==  Address 0x100e098e6 is 0 bytes after a block of size 6 alloc'd
==5170==    at 0x1000CB626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==5170==    by 0x10001AF50: ft_strnew (in ./42sh)
==5170==    by 0x10000C92C: lex_an_cut_quotes (lex_asig_name2.c:22)
==5170==    by 0x1000109DA: lex_parse_tkn_value (lex_val_tkn_processing.c:60)
==5170==    by 0x10000EFC7: lex_fill_value_pos (lex_get_tkn.c:59)
==5170==    by 0x10000EF5C: lex_get_next_tkn (lex_get_tkn.c:48)
==5170==    by 0x10000F466: lex_get_tkns (lex_lexer.c:39)
==5170==    by 0x100002164: ft_system (main.c:39)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==    by 0x100002217: main (main.c:72)
==5170== 
==5170== Invalid read of size 1
==5170==    at 0x10001A3D0: ft_strdup (in ./42sh)
==5170==    by 0x100011A16: parse_word (word_list.c:34)
==5170==    by 0x100011821: word_list (word_list.c:118)
==5170==    by 0x100011A3A: parse_word (word_list.c:35)
==5170==    by 0x100011821: word_list (word_list.c:118)
==5170==    by 0x100011501: parse_ass_words (parse.c:20)
==5170==    by 0x100011410: parse_pipe (parse.c:26)
==5170==    by 0x10001132C: parse_logical (parse.c:39)
==5170==    by 0x100011278: parse (parse.c:50)
==5170==    by 0x1000021C6: ft_system (main.c:46)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==    by 0x100002217: main (main.c:72)
==5170==  Address 0x100e098e6 is 0 bytes after a block of size 6 alloc'd
==5170==    at 0x1000CB626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==5170==    by 0x10001AF50: ft_strnew (in ./42sh)
==5170==    by 0x10000C92C: lex_an_cut_quotes (lex_asig_name2.c:22)
==5170==    by 0x1000109DA: lex_parse_tkn_value (lex_val_tkn_processing.c:60)
==5170==    by 0x10000EFC7: lex_fill_value_pos (lex_get_tkn.c:59)
==5170==    by 0x10000EF5C: lex_get_next_tkn (lex_get_tkn.c:48)
==5170==    by 0x10000F466: lex_get_tkns (lex_lexer.c:39)
==5170==    by 0x100002164: ft_system (main.c:39)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==    by 0x100002217: main (main.c:72)
==5170== 
==5170== Invalid read of size 1
==5170==    at 0x10001A3E5: ft_strdup (in ./42sh)
==5170==    by 0x100011A16: parse_word (word_list.c:34)
==5170==    by 0x100011821: word_list (word_list.c:118)
==5170==    by 0x100011A3A: parse_word (word_list.c:35)
==5170==    by 0x100011821: word_list (word_list.c:118)
==5170==    by 0x100011501: parse_ass_words (parse.c:20)
==5170==    by 0x100011410: parse_pipe (parse.c:26)
==5170==    by 0x10001132C: parse_logical (parse.c:39)
==5170==    by 0x100011278: parse (parse.c:50)
==5170==    by 0x1000021C6: ft_system (main.c:46)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==    by 0x100002217: main (main.c:72)
==5170==  Address 0x100e098e6 is 0 bytes after a block of size 6 alloc'd
==5170==    at 0x1000CB626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==5170==    by 0x10001AF50: ft_strnew (in ./42sh)
==5170==    by 0x10000C92C: lex_an_cut_quotes (lex_asig_name2.c:22)
==5170==    by 0x1000109DA: lex_parse_tkn_value (lex_val_tkn_processing.c:60)
==5170==    by 0x10000EFC7: lex_fill_value_pos (lex_get_tkn.c:59)
==5170==    by 0x10000EF5C: lex_get_next_tkn (lex_get_tkn.c:48)
==5170==    by 0x10000F466: lex_get_tkns (lex_lexer.c:39)
==5170==    by 0x100002164: ft_system (main.c:39)
==5170==    by 0x10000233D: shell_start (main.c:61)
==5170==    by 0x100002217: main (main.c:72)
==5170==

**Comment by OlegMulko** [comment]
OK!
