### ISSUE TITLE
waiting for prompt

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#302]
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>  ps a | grep 'base64' | grep -v 'grep'
>
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>  ps a | grep 'base64'
>
>
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>

**Comment by fica99** [comment]
cho "Notice me senpai"

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru /private
$> echo 'No error' || echo 'You cant see me'
>
aashara- at-a1.21-school.ru /private
$>

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru /private
$> set | grep -E '(a|b)='
>
aashara- at-a1.21-school.ru /private
$>

**Comment by OlegMulko** [comment]
OK!
