### ISSUE TITLE
redir bug

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#337]
aashara- at-b1.21-school.ru ~/Desktop/42sh
$> ls > /tmp/ftsh_ls_out /
aashara- at-b1.21-school.ru ~/Desktop/42sh
$> cat /tmp/ftsh_ls_out
Applications
Library
Network
System
Users
Volumes
backup
bin
cores
dev
etc
exam
goinfre
home
installer.failurerequests
net
nfs
private
sbin
tmp
usr
var
aashara- at-b1.21-school.ru ~/Desktop/42sh
$> < /tmp/ftsh_ls_out cat -e >> /tmp/ftsh_ls_out
aashara- at-b1.21-school.ru ~/Desktop/42sh
$> cat /tmp/ftsh_ls_out
Applications
Library
Network
System
Users
Volumes
backup
bin
cores
dev
etc
exam
goinfre
home
installer.failurerequests
net
nfs
private
sbin
tmp
usr
var
aashara- at-b1.21-school.ru ~/Desktop/42sh
$> < /tmp/ftsh_ls_out cat -e >> /tmp/ftsh_ls_out
aashara- at-b1.21-school.ru ~/Desktop/42sh
$> cat /tmp/ftsh_ls_out
Applications
Library
Network
System
Users
Volumes
backup
bin
cores
dev
etc
exam
goinfre
home
installer.failurerequests
net
nfs
private
sbin
tmp
usr
var
aashara- at-b1.21-school.ru ~/Desktop/42sh
$>

**Comment by mmarti42** [comment]
fixed

**Comment by mmarti42** [comment]
fixed
