### ISSUE TITLE
double error messgs

### ISSUE THREAD

**Issue by Kugumi** [fica99/42sh#386]
test &&

Не выводит ошибку сразу (?), после control+D две ошибки:

> 42sh: syntax error: unexpected end of file
> 42sh: syntax error near unexpected token: `&'

**Comment by Kugumi** [comment]
jijerde at-b2.21-school.ru /
$> &&
> 
42sh: syntax error: unexpected end of file
42sh: syntax error near unexpected token: `&'
jijerde at-b2.21-school.ru /
$> ||
> 
42sh: syntax error: unexpected end of file
> 
42sh: syntax error: unexpected end of file
jijerde at-b2.21-school.ru /
$> ||
> 
42sh: syntax error: unexpected end of file
> 
42sh: syntax error: unexpected end of file
jijerde at-b2.21-school.ru /
$>

**Comment by fica99** [comment]
aashara- at-c2.21-school.ru ~/Desktop/42sh
$> ls EGW'
>
42sh: unexpected EOF while looking for matching '''
42sh: lex: unexpected syntax error
aashara- at-c2.21-school.ru ~/Desktop/42sh
