### ISSUE TITLE
error instead of execution ls

### ISSUE THREAD

**Issue by Kugumi** [fica99/42sh#387]
test 1=2 && ls

> 42sh: lex: unexpected syntax error

**Comment by Kugumi** [comment]
ls > toto ; date >> toto ; >> toto ls ; < toto cat ;

> 42sh: syntax error near unexpected token: `>>'

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> |
> ls
42sh: syntax error near unexpected token: `|'
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> | 
> 
42sh: syntax error: unexpected end of file
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> echo -e 'toto\nplop\nplip\n' > salut
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> 


bash-3.2$ echo -e 'toto\nplop\nplip\n' > salut
bash-3.2$

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> |
> ls
42sh: syntax error near unexpected token: `|'
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> | 
> 
42sh: syntax error: unexpected end of file
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>
