### ISSUE TITLE
escaping characters

### ISSUE THREAD

**Issue by Kugumi** [fica99/42sh#397]
В echo должно прийти два слэша, приходит один

echo -e \\x38 petits\\x20chats boivent son lait\\x21

> x38 petitsx20chats boivent son laitx21

**Comment by Kugumi** [comment]
Тут наоборот слэш теперь не выводится, а должен

echo -e \\38 petits\\20chats boivent son lait\\21

> 38 petits20chats boivent son lait21

**Comment by fica99** [comment]
bash-3.2$ echo -e "\t\t    ls\t     \t-l    \t\t  \t -a /usr   \t\t"
                    ls          -l                       -a /usr   
bash-3.2$ 


aashara- at-a1.21-school.ru /usr
$> \t\t    ls\t     \t-l    \t\t  \t -a /usr   \t\t
42sh: command not found: tt
aashara- at-a1.21-school.ru /usr
$> echo -e "\t\t    ls\t     \t-l    \t\t  \t -a /usr   \t\t"
tt    lst     t-l    tt  t -a /usr   tt
aashara- at-a1.21-school.ru /usr
$>

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> |
> ls
42sh: syntax error near unexpected token: `|'
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> | 
> 
42sh: syntax error: unexpected end of file
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>

**Comment by fica99** [comment]
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> echo -e 'toto\nplop\nplip\n' > salut
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> 


bash-3.2$ echo -e 'toto\nplop\nplip\n' > salut
bash-3.2$

**Comment by fica99** [comment]
> В echo должно прийти два слэша, приходит один
> 
> echo -e \x38 petits\x20chats boivent son lait\x21
> 
> > x38 petitsx20chats boivent son laitx21

Это твой баг в echo, а не Олега
Исправляй эхо срочно

**Comment by fica99** [comment]
bash-3.2$ echo -e 'toto\nplop\nplip\n' > salut
bash-3.2$ echo -e \\x38 petits\\x20chats boivent son lait\\x218 petits chats boivent son lait!
bash-3.2$ echo -e \\x38 petits\\x20chats boivent son lait\\x21
8 petits chats boivent son lait!
bash-3.2$ ls \\x38 petits\\x20chats boivent son lait\\x21
ls: \x38: No such file or directory
ls: boivent: No such file or directory
ls: lait\x21: No such file or directory
ls: petits\x20chats: No such file or directory
ls: son: No such file or directory
bash-3.2$  \t\t ls\t \t-l \t\t \t -a /usr \t\t
bash: tt: command not found
bash-3.2$ " \t\t ls\t \t-l \t\t \t -a /usr \t\t"
bash:  \t\t ls\t \t-l \t\t \t -a /usr \t\t: No such file or directory
bash-3.2$ " \t\t ls\t \t-l \t\t \t -a /usr \t\t    \\"
bash:  \t\t ls\t \t-l \t\t \t -a /usr \t\t    \: No such file or directory
bash-3.2$ " \t\t ls\t \t-l \t\t \t -a /usr \t\t    \\"
bash:  \t\t l



aashara- at-a1.21-school.ru ~/Desktop/42sh
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> echo -e \\x38 petits\\x20chats boivent son la
it\\x21
x38 petitsx20chats boivent son laitx21
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>  
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> echo \t
t
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> ls \t
ls: t: No such file or directory
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>  \t\t ls\t \t-l \t\t \t -a /usr \t\t
42sh: command not found: tt
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>  \t\t ls\t \t-l \t\t \t -a /usr \t\t
42sh: command not found: tt
aashara- at-a1.21-school.ru ~/Desktop/42sh
$>  \t\t ls\t \t-l \t\t \t -a /usr \t\t
42sh: command not found: tt
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> " \t\t ls\t \t-l \t\t \t -a /usr \t\t"
42sh: no such file or directory:  tt lst t-l tt t -a /usr tt
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> '\t\t ls\t \t-l \t\t \t -a /usr \t\t'
42sh: no such file or directory: \t\t ls\t \t-l \t\t \t -a /usr \t\t
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> '\t\t ls\t \t-l \t\t \t -a /usr \t\t  \\'
> 
aashara- at-a1.21-school.ru ~/Desktop/42sh
$> "\t\t ls\t \t-l \t\t \t -a /usr \t\t \\"
>
