### ISSUE TITLE
invalid exit code

### ISSUE THREAD

**Issue by Kugumi** [fica99/42sh#398]
jijerde at-b2.21-school.ru ~/42finality
$> ./42sh
jijerde at-b2.21-school.ru ~/42finality
$> exit 20
jijerde at-b2.21-school.ru ~/42finality
$> echo $?
5120

**Comment by HumanBean17** [comment]
lcrawn at-l3.21-school.ru ~/42refactor
$> exit 20
at-l3% echo $?
20
at-l3% ./42sh
lcrawn at-l3.21-school.ru ~/42refactor
$> exit 50
at-l3% echo $?
50
at-l3%
