### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#43]
==32384== 4,098 bytes in 1 blocks are definitely lost in loss record 54 of 55
==32384==    at 0x1000AE626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==32384==    by 0x10000D53C: ft_memalloc (in ./42sh)
==32384==    by 0x1000010BF: init_curr_pwd (in ./42sh)
==32384==    by 0x10000C991: init_global_var (in ./42sh)
==32384==    by 0x10000C77D: main (in ./42sh)
==32384==

**Comment by mmarti42** [comment]
Какой тест?

**Comment by fica99** [comment]
> Какой тест?

valgrind --leak-check=full  ./42sh
И сразу exit
