### ISSUE TITLE
jobs bug

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#441]
aashara aashara ~/projects/42sh
$> echo $((2/0))
42sh: calc: unexpected error 
aashara aashara ~/projects/42sh
$> jobs
[1]+ running: echo 
aashara aashara ~/projects/42sh
$>

**Comment by fica99** [comment]
aashara aashara ~/projects/42sh
$> echo

aashara aashara ~/projects/42sh
$> jobs
[1]+ running: echo 
aashara aashara ~/projects/42sh
$> echo $PWD
/home/aashara/projects/42sh
aashara aashara ~/projects/42sh
$> jobs
[1]+ running: echo 
aashara aashara ~/projects/42sh
$>

**Comment by mmarti42** [comment]
fixed, need to test
