### ISSUE TITLE
Ft_readline

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#59]
- Main function for reading line(Prompt is a welcome message, mode is a reading mode(EMACS, VI, NOEDIT)).
`char	*ft_readline(char *prompt, t_rl_mode mode);`

- Before using this function you need to init it:
`void	init_readline(void);`

- After using it you need to free data:
`void	free_readline(void);`.

- If you want to add line to history, use this function:
`void	add_to_history_buff(char *line);`
(Line is an adding line).

- If you want to get history expansion, use this function:
`char	*get_hist_expansions(char *line);`
(Line is a history expansion:
∗ !!
∗ !word
∗ !number
∗ !-number
without first symbol)

**Comment by mmarti42** [comment]
Нужно, чтобы ридлайн в ответ на SIGINT прерывал ввод и возвращал NULL, чтобы прервать heredoc

**Comment by mmarti42** [comment]
**команда:** cat < author

==71479== 5 bytes in 1 blocks are definitely lost in loss record 2 of 56
==71479==    at 0x1000BE626: malloc (in /Users/mmarti/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==71479==    by 0x100012B34: ft_strdup (in ./42sh)
==71479==    by 0x10000BE32: ft_readline (rl_main.c:23)
==71479==    by 0x10000DF99: term_start (ft_term.c:49)
==71479==    by 0x10000DEF8: main (ft_term.c:28)
