### ISSUE TITLE
Compilation debug version

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#74]
--->Compile /Users/aashara-/Desktop/42sh/jobs/objs/init_jobs.o
srcs/init_jobs.c:14:8: error: no member named '__stdinp' in 'struct s_job'
    j->stdin = STDIN_FILENO;
    ~  ^
/usr/include/stdio.h:216:15: note: expanded from macro 'stdin'
#define stdin   __stdinp
                ^
srcs/init_jobs.c:15:8: error: no member named '__stdoutp' in 'struct s_job'; did you mean 'stdout'?
    j->stdout = STDOUT_FILENO;
       ^~~~~~
       stdout
/usr/include/stdio.h:217:16: note: expanded from macro 'stdout'
#define stdout  __stdoutp
                ^
../includes/../jobs/includes/jobs.h:25:9: note: 'stdout' declared here
    int stdout; /* standard i/o channels */
        ^
srcs/init_jobs.c:16:8: error: no member named '__stderrp' in 'struct s_job'; did you mean 'stderr'?
    j->stderr = STDERR_FILENO;
       ^~~~~~
       stderr
/usr/include/stdio.h:218:16: note: expanded from macro 'stderr'
#define stderr  __stderrp
                ^
../includes/../jobs/includes/jobs.h:26:9: note: 'stderr' declared here
    int stderr;  
        ^
3 errors generated.
make[3]: *** [objs/init_jobs.o] Error 1
make[2]: *** [jobs] Error 2
make[1]: *** [compilation] Error 2
make: *** [42sh] Error 2

**Comment by mmarti42** [comment]
solved
