### ISSUE TITLE
pwd memory leak

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#83]
$> pwd
==95802== Conditional jump or move depends on uninitialised value(s)
==95802==    at 0x100001D3A: pwd (cd.c:101)
==95802==    by 0x1000032DE: find_command (exec.c:52)
==95802==    by 0x10000317B: make_command (exec.c:32)
==95802==    by 0x100003665: interpret_ast (interpretator.c:27)
==95802==    by 0x10000F452: check_valid_string (ft_term.c:66)
==95802==    by 0x10000F3C6: term_start (ft_term.c:50)
==95802==    by 0x10000F318: main (ft_term.c:28)
==95802==
/Users/aashara-/Desktop/42sh

**Comment by mmarti42** [comment]
solved
