### ISSUE TITLE
cd error

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#90]
Our input / output:

$> cd -P /tmp
aashara-@su-j2.21-school.ru:/tmp
$> pwd
/tmp
aashara-@su-j2.21-school.ru:/tmp
$> /bin/pwd
/tmp
aashara-@su-j2.21-school.ru:/tmp
$> 

Correct:
$ cd -P /tmp

/private/tmp ⌚ 19:38:49
$ pwd
/private/tmp

/private/tmp ⌚ 19:39:47
$ /bin/pwd
/private/tmp

**Comment by mmarti42** [comment]
fixed
