### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by fica99** [fica99/42sh#91]
==94700== 48 bytes in 2 blocks are definitely lost in loss record 24 of 57
==94700==    at 0x1000B8626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==94700==    by 0x10000F6F4: ft_strdup (in ./42sh)
==94700==    by 0x1000023E0: change_wdir (rewrite_cwd.c:97)
==94700==    by 0x100001D0E: cd (cd.c:86)
==94700==    by 0x10000323E: find_command (exec.c:42)
==94700==    by 0x1000031EB: make_command (exec.c:32)
==94700==    by 0x1000036D5: interpret_ast (interpretator.c:27)
==94700==    by 0x10000F4C2: check_valid_string (ft_term.c:66)
==94700==    by 0x10000F436: term_start (ft_term.c:50)
==94700==    by 0x10000F388: main (ft_term.c:28)

**Comment by fica99** [comment]
==7840== 4,098 bytes in 1 blocks are definitely lost in loss record 55 of 56
==7840==    at 0x1000B8626: malloc (in /Users/aashara-/.brew/Cellar/valgrind/3.14.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==7840==    by 0x10001012C: ft_memalloc (in ./42sh)
==7840==    by 0x10000166F: init_curr_pwd (cd.c:17)
==7840==    by 0x10000F551: init_global_var (global_var.c:33)
==7840==    by 0x10000F319: main (ft_term.c:26)
==7840==

**Comment by mmarti42** [comment]
fixed
